[package]
name = "miel"
version = "0.0.2"
edition = "2021"

[[bin]]
name = "miel"
path = "src/main.rs"

[dependencies]
env_logger = "0.11.8"
log = "0.4.27"
clap = { version = "4.5.46", features = ["derive"]}
clap_builder = "4.5.46"
