bind_address = "127.0.0.1"
storage_path = "/var/lib/myapp"
web_ui_enabled = true
web_ui_port = 3000
max_sessions = 100
session_timeout_secs = 3600

[ip_filter]
whitelist_mode = false

[[ip_filter.allowed_ranges]]
start = "0.0.0.0"
end = "255.255.255.255"

[[ip_filter.blocked_ranges]]
start = "192.168.1.0"
end = "192.168.1.1"

[port_filter]

[[port_filter.allowed_ports]]
start = 1
end = 65535

[[port_filter.blocked_ports]]
start = 22
end = 22
