name: Docs

on:
  pull_request:
    paths:
      - "docs/**"
  push:
    branches: [main, dev]
    paths:
      - "docs/**"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: davidB/rust-cargo-make@v1
      - uses: swatinem/rust-cache@v2
        with:
          workspaces: |
            src/core -> target
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Lint Markdown documentation
        run: cargo make doc-lint