name: Release

on:
  pull_request:
    tags:
      - "v*"
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: src/webui/package-lock.json
      - name: Restore cargo cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build production binary
        run: cargo make prod

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: src/core/target/release/miel
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
