name: Release

# on:
#   workflow_run:
#     workflows: ["CI"]
#     types:
#       - completed

permissions:
  contents: write
  packages: write
  security-events: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.conclusion == 'success'  }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v5

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: target/release/

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
